type Welcome {
  guildId: String!
  message: String
  channelId: String
  afterAuth: Boolean
  enabled: Boolean!
}

input CreateWelcomeInput {
  guildId: String!
  message: String
  channelId: String!
  afterAuth: Boolean!
  enabled: Boolean
}

input UpdateWelcomeInput {
  guildId: String
  message: String
  channelId: String
  enabled: Boolean!
  afterAuth: Boolean!
}

type RemoveWelcome {
  ok: Boolean
}

type Query {
  welcome(guildId: String!): Welcome
}

type Mutation {
  createWelcome(guild: CreateWelcomeInput!): Welcome!
  updateWelcome(guild: UpdateWelcomeInput!): Welcome!
  removeWelcome(guildId: String!): RemoveWelcome
}
