type Auth {
  enabled: Boolean
  roleId: String
  guildId: String
}

input UpdateAuthInput {
  guildId: String
  roleId: String
  enabled: Boolean
}

input CreateAuthInput {
  guildId: String
  roleId: String
  enabled: Boolean
}

type Query {
  auth(guildId: String!): Auth
}

input RemoveAuthInput {
  guildId: String!
}

type Mutation {
  updateAuth(guild: UpdateAuthInput!): Auth!
  removeAuth(guildId: String!): Auth!
  createAuth(guild: CreateAuthInput!): Auth!
}
